// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: query.sql

package pages_repo

import (
	"context"
)

const create = `-- name: Create :one
insert into pages (
	title,
	user_id
) values (
	$1,
	$2
) returning id, title, user_id
`

type CreateParams struct {
	Title  string
	UserID int64
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Page, error) {
	row := q.db.QueryRow(ctx, create, arg.Title, arg.UserID)
	var i Page
	err := row.Scan(&i.ID, &i.Title, &i.UserID)
	return i, err
}

const getById = `-- name: GetById :one
select
	id, title, user_id
from
	pages p
where
	p.id = $1
`

func (q *Queries) GetById(ctx context.Context, id int32) (Page, error) {
	row := q.db.QueryRow(ctx, getById, id)
	var i Page
	err := row.Scan(&i.ID, &i.Title, &i.UserID)
	return i, err
}
