CREATE TABLE pages (
	id serial PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	user_id BIGINT NOT NULL REFERENCES users(id),
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);